### ISSUE TITLE
Small Error Handling Error... 

### ISSUE THREAD

**Issue by skidzTweak** [SleepWalker/hoauth#13]
Found a small bug while debugging my setup... 

https://github.com/SleepWalker/hoauth/blob/master/HOAuthAction.php#L358
need to change:
$user->errors
to
$profile->errors

Found this because my test account had a last name of "." 

Error thrown after fixed was:
array (
'last_name' => 
array (
0 => 'Last Name is too short (minimum is 3 characters).',
),
)

It would actually be awesome if it could prompt the user to update the field if something like this happens.. but might be pie in the sky...

**Comment by SleepWalker** [comment]
Yet this extension can do so only for `User` model (I am about field update). For `Profile` I think that I will make this feature in the future, but I can't promise that this will be soon.
Thank you for a report!
