### ISSUE TITLE
user cancellation

### ISSUE THREAD

**Issue by ffarandole** [SleepWalker/hoauth#14]
1. Sign in with Facebook credentials from your application
2. Refuse that your application access to facebook data

Then you are facing following error: 
"Trying to get property of non-object"
HOAuthAction.php line 178

It seems that exception #5 is not handled. My current fix is the following:

Change in UserOAuth.php at line 215:

catch( Exception $e )
{
    $error = "";
    switch( $e->getCode() )
    { 
        case 6 : //$error = "User profile request failed. Most likely the user is not connected to the provider and he should to authenticate again."; 
        case 7 : //$error = "User not connected to the provider."; 
        $this->logout();
        return $this->authenticate($provider);
        break;
    }
}

into

catch( Exception $e )
{
    $error = "";
    switch( $e->getCode() )
    { 
        default:
        $this->logout();
        throw $e;
        break;
        case 6 : //$error = "User profile request failed. Most likely the user is not connected to the provider and he should to authenticate again."; 
        case 7 : //$error = "User not connected to the provider."; 
        $this->logout();
        return $this->authenticate($provider);
        break;
    }
}

But i'm doubting of myself, this issue seems too obvious...

**Comment by marianoarga** [comment]
@ffarandole if you throw it there, the code breaks, you should put it after the loop, anyway, make a pull request :)

```
catch( Exception $e )
    {
        $error = "";
        switch( $e->getCode() )
        {
            case 6 : //$error = "User profile request failed. Most likely the user is not connected to the provider and he should to authenticate again."; 
            case 7 : //$error = "User not connected to the provider."; 
            $this->logout();
            return $this->authenticate($provider);
            break;
        }
        throw $e;
    }
```

**Comment by marianoarga** [comment]
Already made this for you in my fork:
https://github.com/SleepWalker/hoauth/pull/18
