### ISSUE TITLE
Error, while saving Profile	model: array ( 'birthday' => array ( 0 => 'The format of Birthday is invalid.', ), )

### ISSUE THREAD

**Issue by ferozfirru** [SleepWalker/hoauth#15]
while logging in with LINKEDIN i am getting this error

**Comment by SleepWalker** [comment]
Hello,

is the birthday date required in your `yii-user` profile? In witch format should be a date specified? (current version of hoauth can not work with additional required fields in `Profile` model, so I need to try to implement this)

**Comment by ferozfirru** [comment]
the yii-user module having the profile table, there the birthday format is like 0000-00-00. But as per i know is the birthday which is coming from the linkedin api also having the same format(iam not sure, but as i saw the code in linkedin.php in providers folder it seems like that).
I am getting this error in the page where it asks for nickname and email for completing the registration(page after redirecting from linkedin authentication).Iam getting this error after filling the nickname and email and submitting the form for completing the registration. 
At least tell me how can i remove/ignore the date-of-birth from saving into the profile model. Iam not able to complete the project. please brother help me.

**Comment by SleepWalker** [comment]
Yes LinkedIn returns birthday, but this value is not used by `hoauth` by default, so this error can be because you have enabled birthday field in `yii-user` module. You should simply make this field not required in `yii-user`.

And one more question: have you changed `attributes` property in `actions()` method of your controller or have you made just basic setup as described [here](https://github.com/SleepWalker/hoauth/wiki/%5Binstall%5D-hoauth-and-yii-user-extension)?

**Comment by ferozfirru** [comment]
by changing the name of the birthday field in the table or deleting the birthday field it will work fine.

**Comment by vjanagaran** [comment]
Hi, still i have same issue even with Facebook

Original error message: Error, while saving Profile model: array ( 'birthday' => array ( 0 => 'The format of Birthday is invalid.', ), )

Deleting Birthday field fixing this, but i need that field

**Comment by SleepWalker** [comment]
currently hoauth cannot work with additional fields in Profile model, but I will make this possible later. For now, I can only suggest you to make Birthday field not required. Than user will be able to log in and, when he want, provide his birthday later.
