### ISSUE TITLE
How to call getUserContacts()?

### ISSUE THREAD

**Issue by tvandame** [SleepWalker/hoauth#17]
$adapterFacebook = UserOAuth::model()->authenticate("Facebook");
$adapterFacebookContacts = $adapterFacebook->getUserContacts();

**Comment by SleepWalker** [comment]
Try to do following:

``` php
$model = UserOAuth::model()->authenticate("Facebook");
$adapterFacebookContacts = $model->adapter->getUserContacts();
```

**Comment by tvandame** [comment]
That worked thanks.....

It seems that I'm loosing authentication with Google+ after being Idle for a bit of time. Is there a method call that I should be using to check the connection and refresh it. Error below etc...

Error: User profile request failed! Google returned an invalid response.

script.php

``` php
$this->hOAuthModelConnectedProviders = $this->hOAuthModel->findUser(Yii::app()->user->id);
$this->hOAuthModelProviders = $this->hOAuthModelConfig['providers'];

foreach ($this->hOAuthModelConnectedProviders as $obj) {
    if ($obj->provider === "Google") {
        $tmpProfile = $obj->adapter->getUserProfile("Google");

        $tmp[$obj->provider] = array('displayName' => $tmpProfile->displayName);
    }
```

Provider Error, It's complaining about a invalid token when I echo out the full error before throwing the exception listed below.

hoauth/hybridauth/Hybrid/Providers/Google.php(60)

``` php
60 throw new Exception( "User profile request failed! {$this->providerId} returned an invalid response.", 6 );
```

**Comment by SleepWalker** [comment]
You can use the method of hybridauth `Hybrid_Auth::getConnectedProviders()` or `Hybrid_Auth::isConnectedWith()`. The first returns the list of authenticated providers and the second true/false in dependency of provider authentication status. So you can try something like this:

``` php
if(!$obj->hybridauth->isConnectedWith('Google'))
    $obj->authenticate('Google');

if ($obj->provider === "Google") {
```
