### ISSUE TITLE
Authentication Framework

### ISSUE THREAD

**Issue by SleepWalker** [SleepWalker/hoauth#19]
Probably we should change authentication framework (for example to [this](https://github.com/opauth/opauth)), because HybridAuth is not maintained...

**Comment by marianoarga** [comment]
Does it has an advantage?

**Comment by PrplHaz4** [comment]
Coincidentally i was just looking into this today.  Based on the author's tweets, opauth may have an uncertain future as well.   Don't know what the next a steps should be....

**Comment by SleepWalker** [comment]
@marianoarga, I have't seen it yet. I only know, that HybridAuth is probably no longer maintained, so it can cause problems in future. Somebody suggested to use opauth... So if you know a better libs you can post them here. This issue is todo for very very future versions of hoauth.

**Comment by SleepWalker** [comment]
@PrplHaz4, hm. This is bad news. Probably I will try to fork HybridAuth, but I don't know if it will be simple to maintain it... or we will find another one good lib.

**Comment by PrplHaz4** [comment]
@uzyn @hybridauth any chance we could get some info/guidance from you?  I have a feeling this discussion may set the stage for how yii2 proceeds in regards to OAuth extensions....etc. @SleepWalker FYI.

**Comment by uzyn** [comment]
Currently @ceeram and I maintain Opauth but due to our work commitments (at least for myself) our updates on v1.x has been rather slow. You can see [@Ceeram's post on state of v1.x](http://ceeram.github.io/blog/2013/06/22/opauth-1-dot-0-alpha-arriving-soon/)

v0.x is stable, and is maintained. You can adopt it if you wish to adopt Opauth.

**Comment by ceeram** [comment]
@uzyn thx for notifying me in this ticket. I will pick up Opauth 1.0 development soon, its mostly done, its mostly documentation work that needs to be done before going to beta. I would prefer your feedback, if there is things we didnt take into account in 1.0 now is the chance to have it changed before actually freezing api. I think a lot of things have been adressed which were hard to get rigth in the 0.4.x series, but ofcourse there might be things that were not known to us. FuelPHP recently implemented Opauth 0.4, but i think 1.0 is a lot cleaner, for instance the addional callback was removed, as it was not needed in 99% of the times. for the few occasions someone would need it, for instance when running Oauth service, its easy to build that extra step yourself. So please have a look at 1.0 of Opauth and let us know your findings. We will be more then happy to improve where we can to fit your needs, while we still can in this stage.

**Comment by ceeram** [comment]
I understand this project is a about integrating hybridauth for yii framework. There also exists another project for Opauth and yii: https://github.com/kahwee/yii-opauth

**Comment by marianoarga** [comment]
@ceeram that project last commit is from May 16, 2012

**Comment by ceeram** [comment]
Just pointing its existence out to you, perhaps you can work together. I dont know what the exact scopes are for both projects, also i am not judging about which one is best. Users will decide what they like best. I just hope to avoid the not-built-here, and duplicate work.

**Comment by marianoarga** [comment]
Agree

**Comment by SleepWalker** [comment]
I will try to start a new brunch with opauth 1.x. But I don't know when I do this... Probably at the weekend.

**Comment by ceeram** [comment]
Nice, if you need some guidance as docs are still lacking for 1.0 just let
me know, or drop by on #opauth on freenode

2013/9/17 Sviatoslav notifications@github.com
