### ISSUE TITLE
Getting hoauth to work on localhost

### ISSUE THREAD

**Issue by kuldeepkod** [SleepWalker/hoauth#22]
Hi....I'm trying to integrate this extension in my customised Yii application on localhost (Windows 7 and XAMPP). When I invoke the login form of my application, I get the CException error "The config.php file doesn't exists". Can you pls help me?
# Honestly, I did not understand the instruction 4 in "README.md" - as in here:
#4. Visit your oauthadmin action (eg. http://yoursite.com/site/oauthadmin) to create the HybridAuth config. For your HybridAuth Endpoint URL use this: http://yoursite.com/site/oauth. After install you can leave install.php in your file system, while it's in Yii protected directory. But you must remove oauthadmin action, or make such rules, that give access only for admin users. Config file can be found at application.config.hoauth

**Comment by SleepWalker** [comment]
In step 2 you should add to your controller the two new actions (`oauth` and `oauthadmin`). Have you done that?

when yes, then you can access the admin action (this is the place, where you can create your config file) by using default Yii route model (if your application is not to much customized). 

So you need to enter the following url in your address bar: `http:://yoursite/{controllerId}/oauthadmin` or `http:://yoursite/{moduleId}/{controllerId}/oauthadmin` (if your controller is a part of the module). Controller id you can determine by controller class name wich has the following format: {id}Controller. So for `SiteController` it will be 'site' and for `GithubController` it will be 'github'. This rules also working for module ids ({id}Module).

BG

**Comment by aleempasha** [comment]
Hai, I am also checking in the localhost i am unable to get what is going on ... could you please help me to solve the issue 
 Below i am sending the image of error check once thanks in advance
![image](https://f.cloud.github.com/assets/5779833/1413036/d4290436-3e0e-11e3-9e85-8005499cd81b.png)

**Comment by SleepWalker** [comment]
@aleempasha this is happening when you submit config form? or when you navigate to the oauthadmin url in your browser? 
Actually it should not happening, because there is called only UserOAuth::getConfigPath() method... I suggest you to download the latest version from here (not from yii site) and try again.

**Comment by black-lotus** [comment]
it's work nicely, step instalataion has worked
but when i've implement with yii-user, i got some error.. this is my screenshot
![screen shot 2014-04-30 at 9 32 22 am](https://cloud.githubusercontent.com/assets/3261560/2837364/5025d156-d016-11e3-8cc5-56e5176afd78.png)

thanks man.

**Comment by SleepWalker** [comment]
can it be, that your yii-user module has different id (not 'user') in your
config.php file (see array element 'modules')?

the second variant is that is no user with specified email

when the second is true, can you say with wich conditions has it happen?
you tried to log in for the first time? wich social network do you use? I
need the information to reproduce this behavior by me

2014-04-30 6:20 GMT+03:00 black lotus notifications@github.com:

**Comment by kursusHC** [comment]
Stumbled upon the same problem, solved it with the following URL, as URL rewriting is not activated : 

> http://localhost/project/index.php?r=user/login/oauthadmin
