### ISSUE TITLE
return url after login and where I put the line of code

### ISSUE THREAD

**Issue by debzar** [SleepWalker/hoauth#23]
I'm triyng to set the return url before logging into a provider. I  read the Issue #20 but in HoAuthAction.php  in which part  of code I put the line?

**Comment by SleepWalker** [comment]
If you use the current version of github - it's support no returnUrl, while there is a popup authentication now (but I think, I will return the support of returnUrl later).
If you use the version which is current on yii's website - you can use that line of code where you want, before the user will be authenticated. You can use setReturnUrl() for example on the sign-in page.

``` php
public function loginAction()
{
  Yii::app()->user()->returnUrl = Yii::app()->createUrl('user/profile');
...
$this->render('your login page view', array('param' => 'val'));
}
```

**Comment by debzar** [comment]
this works for me...  in site ontroller
 public function hoauthAfterLogin(){

```
    Yii::app()->user->setReturnUrl('contact');
    $this->redirect(Yii::app()->user->returnUrl);

}    
```

**Comment by SleepWalker** [comment]
Oh yes. This is also a good approach!
