### ISSUE TITLE
attributes country and city

### ISSUE THREAD

**Issue by debzar** [SleepWalker/hoauth#24]
'attributes' => array(
                'email' => 'email',
                'name' => 'firstName',
                'lastName' => 'lastName',
                'gen' => 'genderShort',
                'birthDate' => 'birthDate',
                'activationstatus' => 1,
                'username'=>'displayName',
                        _____________________
                        'country'=>'country',
                        'city'=>'city',
                        ____________________

in my database  the fileds country and city return null, how I add more attributes

**Comment by SleepWalker** [comment]
I think, I haven't understood you. What do you mean 'return null'? And what does it mean more attributes?

**Comment by debzar** [comment]
Well, sorry for my english.
I want to get the country and city of the user's profile. But when I try with the information found in http://hybridauth.sourceforge.net/userguide/Profile_Data_User_Profile.html", it doesn´t work.

---

'country'=>'country',
'city'=>'city', 

---

**Comment by SleepWalker** [comment]
The city/country will be returned as string, so you need to check if `city` and `country` columns in your db has char/text type.

And the one more thing: it can be, that the social network returns no city/country

**Comment by re1naldo** [comment]
> And the one more thing: it can be, that the social network returns no city/country

It happened to me. I tried to retrieve `country` from Facebook account but it returned empty. In Google account, both `birthDate` and `country` fields were empty. Those fields have been filled properly in the related social network profiles. 

Is this an issue of HybridAuth? Or do some social network providers not allow us to retrieve those fields?

**Comment by SleepWalker** [comment]
I think, this depends on user's settings and the scope of auth request: https://developers.facebook.com/docs/facebook-login/permissions/

This is what is returned to me:

``` php
object(Hybrid_User_Profile)[67]
  public 'identifier' => string '1669566350' (length=10)
  public 'webSiteURL' => string '' (length=0)
  public 'profileURL' => string 'https://www.facebook.com/sviatoslav.danylenko' (length=45)
  public 'photoURL' => string 'https://graph.facebook.com/1669566350/picture?width=150&height=150' (length=66)
  public 'displayName' => string 'Святослав Даниленко' (length=37)
  public 'description' => string '' (length=0)
  public 'firstName' => string 'Святослав' (length=18)
  public 'lastName' => string 'Даниленко' (length=18)
  public 'gender' => string 'male' (length=4)
  public 'language' => null
  public 'age' => null
  public 'birthDay' => int 3
  public 'birthMonth' => int 9
  public 'birthYear' => int 1991
  public 'email' => string 'mymail@mail.com' (length=12)
  public 'emailVerified' => string 'mymail@mail.com' (length=12)
  public 'phone' => null
  public 'address' => null
  public 'country' => null
  public 'region' => string '' (length=0)
  public 'city' => null
  public 'zip' => null
```

so there is a birth date (field `birthDate` is made in my extension from three fields of profile, that returned by HybridAuth), but no country.

**Comment by re1naldo** [comment]
I see. Beside Facebook, Google users also have option not to make certain fields (like birth date) visible to public (so that they may not be always accessible).
