### ISSUE TITLE
Property "User.fname" is not defined

### ISSUE THREAD

**Issue by housebee** [SleepWalker/hoauth#29]
I click the facebook link, but got the following error. Where is User.fname is defined? Did I miss any step during installation?

"Unspecified error. 

Original error message: Property "User.fname" is not defined."

**Comment by SleepWalker** [comment]
In your oauth action config you have the following lines (this lines was in example and I think, that you copy pasted them without any change):

``` php
'attributes' => array(
          'email' => 'email',
          'fname' => 'firstName',
          'lname' => 'lastName',
          'gender' => 'genderShort',
          'birthday' => 'birthDate',
          // you can also specify additional values, 
          // that will be applied to your model (eg. account activation status)
          'acc_status' => 1,
        ),
```

the key of that array (e.g. 'fname') is the attribute name of your `User` model and the value is the value of fields of data, that is returned from social network. So you need to update array keys to much your `User` model (or delete them, if you don't need some of them)

**Comment by housebee** [comment]
I removed these mapping, it works. Thanks a lot.
