### ISSUE TITLE
How to Call getUserContacts() method which is defined in google.php under providers directory

### ISSUE THREAD

**Issue by aleempasha** [SleepWalker/hoauth#30]
hai,

```
   I need the contacts of a particular user so i think getUserContacts() method is helpful to get the contacts can any one help me on how to call this method from a controller .
```

thanks in advance....

**Comment by SleepWalker** [comment]
You can not use that method directly. You should use the fields of profile object, that is returned by HybridAuth: http://hybridauth.sourceforge.net/userguide/Profile_Data_User_Profile.html

You can setup wich field of profile corresponds to your `User` model in HOAuthAction options as described [here](https://github.com/SleepWalker/hoauth#installation-and-usage) in 2nd step.

Another possibility is to use UserOAuth model to get access to profile directly in your code as described [here](https://github.com/SleepWalker/hoauth#useroauth-model)

You can also authenticate the user by your hand and than get his profile, e.g.:

``` php
$oAuth = UserOAuth::model()->authenticate('Google');
$userProfile = $oAuth->profile;
```
