### ISSUE TITLE
Prepopulated username contains illegal characters (spaces) after Facebook sign-in

### ISSUE THREAD

**Issue by simonmesmith** [SleepWalker/hoauth#31]
When mew users log in with Facebook, they must enter a username before completing their registration with the website. The username field is prepopulated with their Facebook name, which contains a space (e.g. "John Smith"). But usernames cannot contain spaces, which causes an error if they try to save the prepopulated username. That's not a great user experience. This may be because I'm using Yii-User, which has it's own set of rules for usernames. Would be great if hoauth could replace spaces with underscores, or remove them, or take some other action to make it easier for users to create a new account.

**Comment by mt3ck** [comment]
This could be fixed by modifying hoauth/models/HUserInfoForm.php line 73.

From:
$this->username = $model->$nameAtt;
To:
$this->username = preg_replace('/[^A-Za-z0-9_]+/', '_', $model->$nameAtt);

**Comment by simonmesmith** [comment]
Thanks. Was wondering where I should find that. Made the change and looks like it's working. Any reason that shouldn't be permanently added to the extension?

**Comment by SleepWalker** [comment]
> Any reason that shouldn't be permanently added to the extension?

This extension was written not only for `yii-user`, that why I haven't done any filtration.
