### ISSUE TITLE
How does it connect with yii-user

### ISSUE THREAD

**Issue by trbsi** [SleepWalker/hoauth#32]
I saw hoauth has it's own database "user_oauth"
I'm wondering how it can connect with yii-user if their table are different. If I'm taking user ID from yii-user table, I guess it's not the same as one from "user_oauth"

**Comment by SleepWalker** [comment]
hoauth uses priimary key of users from the User table of `yii-user` extension. In `user_oauth` is stored only authentication information from social network.
