### ISSUE TITLE
I am Unable to fetch all contacts

### ISSUE THREAD

**Issue by aleempasha** [SleepWalker/hoauth#33]
in getUserContacts() method i am getting only 25 contacts. But in my Gmail i have 470 contacts... can i know where is the main problem....

**Comment by SleepWalker** [comment]
Actually I haven't used this feature of HybridAuth. In code of Google provider you can see the value of 500 by default:
https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/Providers/Google.php#L95

You can play with the line 98 for example with hardcoded contacts amount value to test what the google will return
