### ISSUE TITLE
Vkontakte provider isn't working

### ISSUE THREAD

**Issue by tbabich** [SleepWalker/hoauth#34]
I didn't find how to add Vkontakte auth.

**Comment by SleepWalker** [comment]
You should do this manualy in hoauth.php, e.g.:

``` php


            "Vkontakte" => array ( 
                "enabled" => true,
                "keys"    => array ( "key" => "", "secret" => "" ) 
            ),
```

probably in the array of the `keys` item should be not `key`, but `id`. I haven't tested it yet...
