### ISSUE TITLE
Using existing email address with Facebook

### ISSUE THREAD

**Issue by rubyberry** [SleepWalker/hoauth#36]
When you sign up using Facebook and use a existing email address it will ask you to change the email address or enter password.

If you change the email address it will allow you access to the existing account when it should create a new one.

**Comment by SleepWalker** [comment]
Oh. This is e serious bug. I will fix it during this week.
Sorry for my bad response

**Comment by kursusHC** [comment]
Is this bug fixed ?

**Comment by SleepWalker** [comment]
Yes. It is already fixed
