### ISSUE TITLE
Setting fields before saving user data

### ISSUE THREAD

**Issue by re1naldo** [SleepWalker/hoauth#38]
Is it possible to set certain fields (like timezone, country, etc.) to related User model before hoauth saves User data? For example, when user registers using Facebook account, application could retrieve various data from his Facebook account and save it to User model.

If it is possible, where should we place the code? I saw we only have 2 callbacks (i.e.  hoauthAfterLogin and hoauthCheckAccess) and User model has been created when they are called.

**Comment by SleepWalker** [comment]
There is one possibility to specify some User model attributes in action property attributes. But this helps only with static value, e.g. status => 1 for all new users.

When you to change some attributes according to the user's social profile, for now, you can only use `hoauthProcessUser($user, $userProfile)` callback. But this callback is responsible for the whole user registration process. So to use it you should copy some code from original `HOAuthAction::processUser()` method.

And another variant could be with edition of User model and using beforeSave() method. For example you already have `country` attribute in your User model, but you don't want to use country name, that is returned by social network. Than you can do the following:
action config:

``` php
public function actions()
{
  ...
    'attributes' => array(
      'socialCountry' => 'country',
    ),
 ...
}
```

Than in your model:

``` php
public function setSocialCountry($country)
{
  $mainland = $this->mainlandByCountry($country);
  $this->timezone = $mainland.'/'.$country; // here is timezone setting

  $countryModel = Country::model()->findByAttributes(array('name' => $country));
  $this->country_id = $countryModel ? $countryModel->primaryKey : new CDbExpression('NULL');
}
```

so you even need no `beforeSave()` method call.

when you need, I can also add one more callback that will be called before user's model saving.

**Comment by re1naldo** [comment]
Sorry for my late response. 

Thank you for such detailed explanation. Very helpful indeed, but the country value that was returned from social network was empty. It may be related to [this issue](https://github.com/SleepWalker/hoauth/issues/24).

**Comment by re1naldo** [comment]
Is it possible to set `country` field in User table with certain value when social network provider returns no `country` data? If I understand your code correctly, `setSocialCountry()` method won't be called when `country` data is empty. Is this true?

**Comment by SleepWalker** [comment]
@re1naldo, it should be actually called. see this function: https://github.com/SleepWalker/hoauth/blob/master/HOAuthAction.php#L440 . So all `HOAuthAction::$attributes` will be setted during model population, even if in profile data it will be an empty field.

You have some more options:
- you can use yii `default` validator for the case when value empty: http://www.yiiframework.com/wiki/56/#hh9
- or define custom validator: http://www.yiiframework.com/wiki/168/create-your-own-validation-rule/
- and, of corse `CActiveRecord::beforeSave()` method

**Comment by re1naldo** [comment]
Please correct me if I am wrong, but if I saw this line (https://github.com/SleepWalker/hoauth/blob/master/HOAuthAction.php#L463), user attribute will only be set when profile data is not empty, won't it?

As  `setSocialCountry()` method was placed in User model, then it won't be called when country data from social network is empty, right?

Anyway, thanks for mentioning `beforeSave()` method. I'm sure it can be used for handling empty fields.

**Comment by SleepWalker** [comment]
> Please correct me if I am wrong, but if I saw this line (https://github.com/SleepWalker/hoauth/blob/master/HOAuthAction.php#L463), user attribute will only be set when profile data is not empty, won't it?

oh, yes. You are right, sorry.

> As setSocialCountry() method was placed in User model, then it won't be called when country data from social network is empty, right?

yes. that's right too

**Comment by re1naldo** [comment]
Ok. Thanks for the clarification.
