### ISSUE TITLE
Hybridauth renewed

### ISSUE THREAD

**Issue by pavlyuts** [SleepWalker/hoauth#39]
Please, be advised that hybridauth lib back to live and found new mantainers. At now a lot of fixes applying, and finally it expected to get the new version tag.

Guess you need to prepare new release of hoauth because some fixes are important.

Have a good luck!

**Comment by SleepWalker** [comment]
Oh, this is a good news! Thank you @pavlyuts. I will examine the changes and merge them into my project as soon as possible

**Comment by pavlyuts** [comment]
You wellcome! ))))))))))
