### ISSUE TITLE
Display form before saving user data

### ISSUE THREAD

**Issue by re1naldo** [SleepWalker/hoauth#40]
Can we display a form after user logs in to his social network account? So before application saves data to User table, it will ask user to accept Terms/Policy and fill certain fields that cannot be retrieved from his social network account. 

As mentioned in issue https://github.com/SleepWalker/hoauth/issues/38, it seems we can use `hoauthProcessUser($user, $userProfile)` callback. However, I'm still not sure how to use it to display form and what code that needs to be copied from `HOAuthAction::processUser()` method.

**Comment by SleepWalker** [comment]
At the moment it can be done only with `hoauthProcessUser` or `hoauthCheckAccess`. `hoauthProcessUser` will be called for new user before registration. But if you use `hoauthProcessUser` you will need to copy-paste the whole data processing (and also change `populateModel`  to be 'public'). 

`hoauthCheckAccess` looks better, but this callback will be called after registration and before user will be logged in. here is the link for some info: https://github.com/SleepWalker/hoauth/wiki/Callbacks

Choose the one, that is better for you and I will right an example of code

P.S. I will implement a better callback, but not now, because I'm very busy with my master work in university.

**Comment by re1naldo** [comment]
I can only use `hoauthProcessUser` callback now because those fields should be filled before user data is saved.

> Choose the one, that is better for you and I will right an example of code

Yes, please, an example would be very helpful. Currently I just added `hoauthProcessUser` to `SiteController` (I removed yii-user part as I don't use yii-user):

```
public function hoauthProcessUser($user, $userProfile)
{
     if ($user->isNewRecord)
          $this->populateModel($user, $userProfile);

      // trying to fill email and username fields
      // NOTE: we display `username` field in our form only if it is required by the model
      if (!$user->isAttributeRequired($this->usernameAttribute))
        $this->usernameAttribute = false;

      $form = new RegistrationForm;
      if (!$form->validate())
      {
        $this->render('registration', array(
                'form'=>$form,
            ));            
        Yii::app()->end();
     }

     // updating attributes in $user model (if needed)
     $user = $form->validUserModel;

     // the model won't be new, if user provided email and password of existing account
     if ($user->isNewRecord) 
     {
        if(!$user->save())
            throw new Exception("Error, while saving {$this->model} model:\n\n" . var_export($user->errors, true));
     }

     return $user;        
}   
```

Not sure if that's correct, but what I don't understand is how do we get submitted data from RegistrationForm (contains fields that need to be filled by user) to that callback?

**Comment by SleepWalker** [comment]
Hello and sorry for my late answer. Here you can use your own model, with the rules you need and the view file, that you want.

For example you want let the new user to register and ask him for additionary data. If the user logins for the first time, but with email of existend account, you probably want to ask him for the password of that account too. For example:

``` php
public function hoauthProcessUser($user, $userProfile)
{
     $form = new RegistrationForm;
     if ($user->isNewRecord)
          $this->populateModel($user, $userProfile);
    else
        $form->scenario = 'confirmPassoword'; // marking, that user should confirm his password

    $valid = false;
    if(isset($_POST['RegistrationForm']))
    {
        $form->attributes = $_POST['RegistrationForm'];
        $valid = $form->validate();
    }


      if (!$valid)
      {
        $this->render('registration', array(
                'form'=>$form,
            ));            
        Yii::app()->end();
     }

     // updating attributes in $user model 
     // here should you can do what you need. you can simply apply the data from RegistrationForm, if the attributes has the same names
     $user->attributes = $form->attributes;

     // the model won't be new, if user provided email and password of existing account
     if ($user->isNewRecord && $form->scenario != 'confirmPassoword') 
     {
        if(!$user->save())
            throw new Exception("Error, while saving {$this->model} model:\n\n" . var_export($user->errors, true));
     }

     return $user;        
}
```

**Comment by re1naldo** [comment]
Ok. Thanks!
