### ISSUE TITLE
Avoiding modification of the user module

### ISSUE THREAD

**Issue by zedrdave** [SleepWalker/hoauth#41]
I have set-up hoauth and it works great. However I would like to avoid modifying the _user_ module files directly and keep them as a clean git submodule in our project (having external modules that cannot be updated easily sounds dangerous in the long term).

It's easy enough inserting the widget in the view with a theme, but is there any way I can avoid modifying the Login Controller's actions in the module file itself?

**Comment by SleepWalker** [comment]
Youc can create your own controller. Lets say OauthController and add the HOAuthAction there. In widget with buttons you can change route of the controller

``` php
$this->widget('...HOAuth', array(
    'route' => 'oauth',
));
```

if you need to do something special after login you can use `OauthController::hoauthAfterLogin($user, $newUser)` callback
