### ISSUE TITLE
Update User Status

### ISSUE THREAD

**Issue by hallstar05** [SleepWalker/hoauth#49]
How do I update a user's status? For example, updating a logged-in (connected) Facebook user's status. 

For example, with hybridauth, I do this:

```
    $adapter = $hybridauth->authenticate( $provider );
    $adapter->setUserStatus($message);
```

But how can I do that using this library?
Thanks.

**Comment by SleepWalker** [comment]
hi @hallstar05, you can do that almost the same way:

``` php
$oAuth = UserOAuth::model()->authenticate( $provider );
$oAuth->adapter->setUserStatus($message);
```

or when you want, you can do that through db

``` php
$oAuth = UserOAuth::model()->findUser(5, "Google");
if($oAuth) {  // this user had used HOAuth earlier
  $oAuth->adapter->setUserStatus($message);
}
```

**Comment by hallstar05** [comment]
This is brilliant! Thanks for helping.

**Comment by SleepWalker** [comment]
not at all :)
