### ISSUE TITLE
problem with popup box

### ISSUE THREAD

**Issue by miteshsc** [SleepWalker/hoauth#50]
Hi @SleepWalker,

Thank you for Awesome work!
I have installed hoauth with yii-user extensions, and everything seems working fine. In hoauth config file i have set configuration something like below

<pre>
return 
    array(
        "base_url" => "http://dev.localhost.com/user/login/oauth",

        "providers" => array ( 
            "Facebook" => array ( 
                "enabled" => true,
                "keys"    => array ( "id" => "FOO", "secret" => "FOO" ),
                "display" => "popup"
            ),
         ),
       )
</pre>

Here is just a sample config for Facebook.

What my problem is, when i click on facebook login button, it shows me a pop up and then i am entering my fb login credential and after successfully login in FB it is not taking me back to parent window but instead of that it shows me website in pop up itself. So  logically it should take me to the website and over there i can select username & email id.

I am not sure how to do this? if you have such config setting then please let me know.
or else i have to make changes widget code.

many thanks in advance!

**Comment by SleepWalker** [comment]
can you provide also the config of HoauthAction? 
Can it be, that on the page where you redirected there is some errors, especially in JS? Because the popup is closed by js code

here is the code after authorisation:

``` php
if($accessCode === 1)
{
    ?>
    <script>
        var returnUrl = <?php echo $this->useUserReturnUrl ? CJavaScript::encode(Yii::app()->user->getReturnUrl(false)) : false; ?>;
        if(window.opener)
        {
            if(returnUrl)
                window.opener.location.href = returnUrl;
            else
                window.opener.location.reload();

            window.close();
        }else{
            window.location.href = returnUrl ? returnUrl : '/';
        }
    </script>
    <?php
    Yii::app()->end();
}
```

so there should be actualy the blank page with the single js script

P.S. Sorry for my long response :(

**Comment by rayleesg** [comment]
Hi there,

I'm getting a slightly different result. My popup window closes, but the main page doesn't return with the uer logged on. Instead, I have to enter in the oauth url directly in the main page for the user to be logged in with my SN.

Any ideas how to get it to log the user in after the popup window closes?

Thanks.
