### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by jeanleon87** [SleepWalker/hoauth#51]
Might upload the complete files of this demo
http://hoauth.hamstercms.com/yii-user/

**Comment by SleepWalker** [comment]
What do you mean? Should I upload the new files or what? The version on the test site has all new features.

**Comment by r3verser** [comment]
He means, upload demo site sources with all needed modules installed. Out of the box complete working demo project. That's a good idea imo.

**Comment by SleepWalker** [comment]
You mean, he wants repo of this site? http://hoauth.hamstercms.com/yii-user/
ok, it can be useful

**Comment by r3verser** [comment]
Exactly! Thanks.:)

**Comment by jeanleon87** [comment]
yeah, that would be helpful

Date: Mon, 25 Aug 2014 21:46:05 -0700

**Comment by SleepWalker** [comment]
Finally, I've done it: https://github.com/SleepWalker/hoauth-demo-site . It uses the latest yii, hoauth and yii-user with my additions

**Comment by marianoarga** [comment]
Thank you for the update @SleepWalker
