### ISSUE TITLE
Login OK but can't call UserOAuth::

### ISSUE THREAD

**Issue by kursusHC** [SleepWalker/hoauth#52]
I have set up hoauth on top of yii-user carefully following the installation guide. 

I can login/register with Gmail provider, and display my profile. 

However when I try the example in the doc : 

```
$userOAuths = UserOAuth::model()->findUser(5); // find all authorizations from user with id=5
foreach($userOAuths as $userOAuth)
{
  $profile = $userOAuth->profile;
  echo "Your email is {$profile->email} and social network - {$userOAuth->provider}<br />";
}
```

I get a "include(UserOAuth.php): failed to open stream: No such file or directory" error. 

phpinfo() shows OAuth is enabled on my server. 

What am I doing wrong ?

**Comment by SleepWalker** [comment]
You should simply import (set on the Yii path) the `UserOAuth` model before you using it:

``` php
Yii::import('ext.hoauth.models.UserOAuth');
$userOAuths = UserOAuth::model()->findUser(5);
...
```

**Comment by kursusHC** [comment]
That was it ! Thanks for your great work.
