### ISSUE TITLE
Widget to display social networks, that connected to the user's local account

### ISSUE THREAD

**Issue by SleepWalker** [SleepWalker/hoauth#8]
This widget will simply aggregate user's social network connections and will display the list of links

``` html
<ul class="hoauthSNList">
<li><a href="linkToProfile">Social network</a></li>
...
</ul>
```

It will be also new column "profile" in db created, where we will cache user's profile object. And of course all widgets should be moved to `widgets` directory.

**Comment by PrplHaz4** [comment]
Caching of a users profile object in db should probably be optional - as (IMO) this could be considered a security/privacy concern.

Are you thinking of using any of Yii's built in caching features?

**Comment by SleepWalker** [comment]
I think that that info in profile object is not so private. In most cases this is email (that we will in any case store in `user` table), name, last name, profile url, avatar url. It can be also info about date of birth, country and city of the user. Here is the [full list](http://hybridauth.sourceforge.net/userguide/Profile_Data_User_Profile.html), but I haven't seen the network, that gives all that fields.

I wanted to add one column in db and serializing profile object there (I can also use Yii caching, but I think that is better simply to add one column in db). The reason for this is that we need a profile url in this widget (and probably something else in future). When we consider not to cache, we have two problems: 
- for each network script must connect sn for the fresh profile copy
- when user must relogging in sn (for example in google) we must ask him to repeat `Logging with Google` button click each time

Probably the best way is to save serialized array but only with profile url (for now), which is changing rarely (so we can cache it forever or for the next time, when user will be logged in) and 100% is not confidential
